config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get '/profile', to: 'users#profile', as: 'user_profile'
  get 'players/:id', to: 'players#show', as: 'player'
  get '/player_image/:id', to: 'players#image', as: 'player_image'
  get '/nation/:id', to: 'players#nation', as: 'player_nation'
  get '/club/:id', to: 'players#club', as: 'player_club'
  get '/nation_image/:id', to: 'players#nation_image', as: 'nation_image'
  get '/club_image/:id', to: 'players#club_image', as: 'club_image'
  get '/league_image/:id', to: 'players#league_image', as: 'league_image'
  get '/squads/:squad_id/add_player/:position', to: 'players#new_for_squad', as: 'new_for_squad_player'




  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :players
  resources :squads do
    resources :squad_players, only: [:create, :destroy]
  end  
  
  

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'


  namespace :api do
    namespace :v1 do
      resources :players, only: [:index]
    end
  end
  
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :squad_players, dependent: :destroy
  has_many :squads, through: :squad_players
end

app/controllers/api/v1/players_controller.rb
module Api
  module V1
    class PlayersController < ApplicationController
      def index
        @players = Player.all
        render json: @players
      end
    end
  end
end

app/controllers/players_controller.rb
require 'httparty'

class PlayersController < ApplicationController
  before_action :set_player, only: [:edit, :update, :destroy]

  def index
    page = params[:page].presence || 1
    players_response = FutdbApiService.fetch_players(page: page)
  
    if players_response && players_response['items'].is_a?(Array)
      filtered_players = filter_players_by_name(players_response['items'], params[:search])
      @players = sort_players(filtered_players, params[:sort])
      @pagination = PaginationWrapper.new(players_response['pagination'])
    else
      @players = []
      @pagination = PaginationWrapper.new({ 'pageTotal' => 0, 'pageCurrent' => 0 })
    end
  end
  
  
  def sort_players(players, sort_criteria)
    return players unless sort_criteria.present?
  
    sorted_players = players.sort_by do |player|
      case sort_criteria
      when 'rating' then -player['rating'].to_i
      when 'pace' then -player['pace'].to_i
      when 'shooting' then -player['shooting'].to_i
      when 'passing' then -player['passing'].to_i
      when 'dribbling' then -player['dribbling'].to_i
      when 'defending' then -player['defending'].to_i
      when 'physicality' then -player['physicality'].to_i
      else player['name']
      end
    end
    sorted_players
  end
  
  def filter_players_by_name(players, search_name, threshold = 2)
    return players if search_name.blank?

    players.select do |player|
      first_name = player['firstName'] || ""
      last_name = player['lastName'] || ""
      levenshtein_distance(first_name.downcase, search_name.downcase) <= threshold ||
        levenshtein_distance(last_name.downcase, search_name.downcase) <= threshold
    end
  end

  

  def levenshtein_distance(str1, str2)
    m = str1.length
    n = str2.length
    return m if n == 0
    return n if m == 0
    matrix = Array.new(m+1) { Array.new(n+1) }
  
    (0..m).each { |i| matrix[i][0] = i }
    (0..n).each { |j| matrix[0][j] = j }
  
    (1..m).each do |i|
      (1..n).each do |j|
        cost = str1[i-1] == str2[j-1] ? 0 : 1
        matrix[i][j] = [matrix[i-1][j] + 1, matrix[i][j-1] + 1, matrix[i-1][j-1] + cost].min
      end
    end
  
    matrix[m][n]
  end
  
  def show
    @player = FutdbApiService.fetch_player_details(params[:id])
  end

  def image
    player_id = params[:id]
    api_key = ENV['FUTDB_API_TOKEN']
    response = HTTParty.get("https://futdb.app/api/players/#{player_id}/image", headers: { "X-AUTH-TOKEN" => api_key })
    send_data response.body, type: response.headers['Content-Type'], disposition: 'inline'
  end

  def nation_image
    nation_id = params[:id]
    api_key = ENV['FUTDB_API_TOKEN']
    response = HTTParty.get("https://futdb.app/api/nations/#{nation_id}/image", headers: { "X-AUTH-TOKEN" => api_key })  
    send_data response.body, type: response.headers['Content-Type'], disposition: 'inline'
  end  

  def club_image
    club_id = params[:id]
    api_key = ENV['FUTDB_API_TOKEN']
    response = HTTParty.get("https://futdb.app/api/clubs/#{club_id}/image", headers: { "X-AUTH-TOKEN" => api_key })  
    send_data response.body, type: response.headers['Content-Type'], disposition: 'inline'
  end 

  def league_image
    league_id = params[:id]
    api_key = ENV['FUTDB_API_TOKEN']
    response = HTTParty.get("https://futdb.app/api/leagues/#{league_id}/image", headers: { "X-AUTH-TOKEN" => api_key })  
    send_data response.body, type: response.headers['Content-Type'], disposition: 'inline'
  end 

  def new_for_squad
    @squad = Squad.find(params[:squad_id])
    @position = params[:position]
    players_response = FutdbApiService.fetch_players(page: params[:page])
    @players = players_response['items'] if players_response && players_response['items'].is_a?(Array)
    @pagination = PaginationWrapper.new(players_response['pagination'])
  end  
  

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to @player, notice: 'Player was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @player.update(player_params)
      redirect_to @player, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @player.destroy
    redirect_to players_url, notice: 'Player was successfully destroyed.'
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :position, :identifier, :api_id, :rating, :nation, :club, :league, :pace, :shooting, :passing, :dribbling, :defending, :physicality)
  end  

end

app/helpers/api/v1/players_helper.rb
module Api::V1::PlayersHelper
end

app/helpers/players_helper.rb
require 'httparty'

module PlayersHelper
  def fetch_nation_name(nation_id)
    api_key = ENV['FUTDB_API_TOKEN']
    response = HTTParty.get("https://futdb.app/api/nations/#{nation_id}", headers: { "X-AUTH-TOKEN" => api_key })
    response.parsed_response['nation']['name'] if response.code == 200
  end

  def fetch_club_name(club_id)
    api_key = ENV['FUTDB_API_TOKEN']
    response = HTTParty.get("https://futdb.app/api/clubs/#{club_id}", headers: { "X-AUTH-TOKEN" => api_key })
    response.parsed_response['club']['name'] if response.code == 200
  end

  def fetch_league_name(league_id)
    api_key = ENV['FUTDB_API_TOKEN']
    response = HTTParty.get("https://futdb.app/api/leagues/#{league_id}", headers: { "X-AUTH-TOKEN" => api_key })
    response.parsed_response['league']['name'] if response.code == 200
  end

  def fetch_card_rarity(rarity_id)
    api_key = ENV['FUTDB_API_TOKEN']
    response = HTTParty.get("https://futdb.app/api/rarities/#{rarity_id}", headers: { "X-AUTH-TOKEN" => api_key })
    response.parsed_response['rarity']['name'] if response.code == 200
  end
end

app/views/players/_player_list.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<div class='overflow-x-auto'>
<table class="min-w-full divide-y divide-gray-200 table-fixed">
  <thead class="bg-gray-50">
    <tr>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-1/4">Name</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Position</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Rating</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Pace</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Shooting</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Passing</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Dribbling</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Defending</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Physicality</th>
    </tr>
  </thead>
  <tbody class="bg-white divide-y divide-gray-200">
  <% if players.any? %>
  <% players.each do |player| %>
    <tr>
      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
        <div class="flex items-center">
          <%= link_to player['name'], player_path(player['id']) %>
          <% if squad_builder && position && squad_id %>
            <%= button_to squad_squad_players_path(
                  squad_id: squad_id,
                  position: position,
                  player_id: player['id']
                ), method: :post, class: 'inline-block text-blue-500 hover:underline ml-2', title: 'Add to Squad' do %>
              <span class="material-icons">add</span>
            <% end %>
          <% end %>
        </div>
      </td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['position'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['rating'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['pace'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['shooting'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['passing'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['dribbling'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['defending'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['physicality'] %></td>
    </tr>
  <% end %>
  <% else %>
    <tr>
      <td colspan="8" class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">No players found</td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

<%# Pagination %>
<div class="text-gray-300 flex items-center justify-center my-4">
  <%= will_paginate @pagination, renderer: WillPaginate::ActionView::LinkRenderer, previous_label: 'Previous', next_label: 'Next', inner_window: 2, outer_window: 0, link_options: { class: 'px-4 py-2 mx-1 border border-indigo-500 rounded-md text-indigo-500 hover:bg-indigo-500 hover:text-white' } %>
</div>

app/views/players/index.html.erb
<h1 class="text-2xl font-bold my-4 text-gray-200">Players</h1>

<%= form_with url: players_path, method: :get, local: true, class: "flex flex-col space-y-4 mb-6" do |form| %>
  <div>
    <%= form.label :search, 'Search by name', class: "block text-sm font-medium text-gray-300" %>
    <%= form.text_field :search, value: params[:search], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50" %>
  </div>
  <div>
    <%= form.label :sort, 'Sort by', class: "block text-sm font-medium text-gray-300" %>
    <%= form.select :sort, options_for_select(['rating', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physicality'].map { |option| [option.titleize, option] }, params[:sort]), {}, { class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", onchange: "this.form.submit();" } %>


  </div>
  <%= form.submit 'Search', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
<% end %>
<%= render 'players/player_list', players: @players, squad_builder: false %>

<div class='overflow-x-auto'>
<table class="min-w-full divide-y divide-gray-200">
  <thead class="bg-gray-50">
    <tr>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Rating</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Pace</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Shooting</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Passing</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Dribbling</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Defending</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Physicality</th>
    </tr>
  </thead>
  <tbody class="bg-white divide-y divide-gray-200">
  <% if @players.any? %>
  <% @players.each do |player| %>
    <tr>
    <tr>
    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
      <%= link_to player['name'], player_path(player['id']) %>
    </td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
      <span class="<%= player_color_class(player['color']) %> rounded-full px-3 py-1">
        <%= player['rating'] %>
      </span>
    </td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['pace'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['shooting'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['passing'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['dribbling'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['defending'] %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= player['physicality'] %></td>
      <% if params[:squad_builder] && params[:position] %>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
        <%= button_to 'Add to Squad', squad_squad_players_path(
              squad_id: params[:squad_id],
              position: params[:position],
              player_id: player['id'],
              return_to: new_squad_path(params[:squad_id])
            ), method: :post, class: 'text-blue-500 hover:underline' %>
      </td>
    <% end %>    
    </tr>
  <% end %>
<% else %>
  <tr>
    <td colspan="8" class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">No players found</td>
  </tr>
<% end %>
  </tbody>
</table>
</div>

<%# Pagination %>
<div class="text-gray-300 flex items-center justify-center my-4">
  <%= will_paginate @pagination, renderer: WillPaginate::ActionView::LinkRenderer, previous_label: 'Previous', next_label: 'Next', inner_window: 2, outer_window: 0, link_options: { class: 'px-4 py-2 mx-1 border border-indigo-500 rounded-md text-indigo-500 hover:bg-indigo-500 hover:text-white' } %>
</div>

app/views/players/new_for_squad.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<h1 class='text-gray-200 font-semibold mb-2'> Choose Player <%= @squad.name %> - Position: <%= @position %></h1>

<%= render 'players/player_list', players: @players, squad_builder: true, position: @position, squad_id: @squad.id %>
<div class='text-gray-200 mb-2'>
<%= link_to squad_path(@squad), class: 'flex items-center text-blue-500 hover:text-blue-700' do %>
  <span class="material-icons">arrow_back</span>
  <span class="ml-2">Back to Squad</span>
<% end %>
</div>

app/views/players/show.html.erb
<div class="max-w-4xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
  <div class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6 bg-gray-100 flex flex-col items-center sm:flex-row justify-between">
  <div class="flex items-center mb-4 sm:mb-0">
    <%= image_tag(player_image_path(@player['id']), alt: @player['name'], class: "player-image mr-4 rounded-full", height: '150', width: '150') %>
    <h1 class="text-3xl leading-6 font-medium text-gray-900"><%= @player['name'] %></h1>
  </div>
  <div class="flex flex-col items-center">
    <span class="<%= player_color_class(@player['color']) %> rounded-full px-3 py-1 text-2xl font-medium mb-2">
      <%= @player['rating'] %>
    </span>
    <div class="bg-gray-50 px-4 py-2 rounded-lg shadow">
      <dt class="text-sm font-medium text-gray-500">Rarity</dt>
      <dd class="mt-1 text-sm text-gray-900"><%= fetch_card_rarity(@player['rarity']) %></dd>
    </div>
  </div>
  </div>
  <div class="border-t border-gray-200">
  <h2 class="px-4 py-2 text-lg font-semibold text-gray-800">Team Info</h2>
  <dl class="sm:grid sm:grid-cols-3 gap-4">
    <div class="bg-gray-50 px-4 py-5 sm:px-6 rounded-lg shadow">
      <dt class="text-sm font-medium text-gray-500">Nation</dt>
      <dd class="mt-1 text-sm text-gray-900"><%= fetch_nation_name(@player['nation']) %></dd>
      <%= image_tag(nation_image_path(@player['nation']), alt: "Nation Flag", class: "nation-flag mt-2", height: '50', width: '50') %>
    </div>
    <div class="bg-gray-50 px-4 py-5 sm:px-6 rounded-lg shadow">
      <dt class="text-sm font-medium text-gray-500">Club</dt>
      <dd class="mt-1 text-sm text-gray-900"><%= fetch_club_name(@player['club']) %></dd>
      <%= image_tag(club_image_path(@player['club']), alt: "Club Flag", class: "club-flag mt-2", height: '50', width: '50') %>
      </div>
    <div class="bg-gray-50 px-4 py-5 sm:px-6 rounded-lg shadow">
      <dt class="text-sm font-medium text-gray-500">League</dt>
      <dd class="mt-1 text-sm text-gray-900"><%= fetch_league_name(@player['league']) %></dd>
      <%= image_tag(league_image_path(@player['league']), alt: "League Flag", class: "league-flag mt-2", height: '50', width: '50') %>
      </div>
  </dl>
  </div>
  <div class="border-t border-gray-200">
    <h2 class="px-4 py-2 text-lg font-semibold text-gray-800">Performance Stats</h2>
    <dl class="sm:grid sm:grid-cols-3 gap-4">
      <% ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physicality'].each do |stat| %>
        <div class="bg-gray-50 px-4 py-5 sm:px-6 rounded-lg shadow">
          <dt class="text-sm font-medium text-gray-500"><%= stat.capitalize %></dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @player[stat] %></dd>
        </div>
      <% end %>
    </dl>
  </div>
    <div class="border-t border-gray-200">
    <h2 class="px-4 py-2 text-lg font-semibold text-gray-800">Personal Info</h2>
    <dl class="sm:grid sm:grid-cols-3 gap-4">
      <% ['height', 'weight', 'gender', 'birthDate', 'age', 'league', 'rarity', 'position', 'skillMoves', 'weakFoot', 'foot', 'attackWorkRate', 'defenseWorkRate', 'totalStats', 'totalStatsInGame'].each do |info| %>
        <div class="bg-gray-50 px-4 py-5 sm:px-6 rounded-lg shadow">
          <dt class="text-sm font-medium text-gray-500"><%= info.titleize %></dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @player[info] %></dd>
        </div>
      <% end %>
    </dl>
  </div>  
  </div>
</div>