config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get '/profile', to: 'users#profile', as: 'user_profile'
  get 'players/:id', to: 'players#show', as: 'player'
  get '/player_image/:id', to: 'players#image', as: 'player_image'
  get '/nation/:id', to: 'players#nation', as: 'player_nation'
  get '/club/:id', to: 'players#club', as: 'player_club'
  get '/nation_image/:id', to: 'players#nation_image', as: 'nation_image'
  get '/club_image/:id', to: 'players#club_image', as: 'club_image'
  get '/league_image/:id', to: 'players#league_image', as: 'league_image'
  get '/squads/:squad_id/add_player/:position', to: 'players#new_for_squad', as: 'new_for_squad_player'




  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :players
  resources :squads do
    resources :squad_players, only: [:create, :destroy]
  end  
  
  

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'


  namespace :api do
    namespace :v1 do
      resources :players, only: [:index]
    end
  end
  
end

app/models/squad.rb
class Squad < ApplicationRecord
  belongs_to :user
  has_many :squad_players, dependent: :destroy
  has_many :players, through: :squad_players
  accepts_nested_attributes_for :squad_players, allow_destroy: true

  POSITIONS = [
    'GK',
    'RB',
    'RCB',
    'LCB',
    'LB',
    'RCM',
    'CM',
    'LCM',
    'RW',
    'LW',
    'ST',
  ].freeze

  def player_for_position(position)
    squad_player = squad_players.find_by(position: position)
    return nil unless squad_player
  
    player_data = FutdbApiService.fetch_player_details(squad_player.player.api_id)
    player_data
  end
  
end

app/controllers/squads_controller.rb
class SquadsController < ApplicationController
  before_action :set_squad, only: [:show, :edit, :update, :destroy]

  def index
    @my_squads = current_user.squads.order(created_at: :desc)
    @user_squads = Squad.where.not(user_id: current_user.id).order(created_at: :desc)
  end

  def show
  end

  def new
    if session[:squad_id]
      @squad = current_user.squads.find_by(id: session[:squad_id])
    end
  
    unless @squad
      @squad = current_user.squads.create
      session[:squad_id] = @squad.id
    end
  end
  

  def create
    @squad = Squad.new(squad_params)
    if @squad.save
      redirect_to @squad, notice: 'Squad was successfully created.'
    else
      render :new
    end
  end

  def edit
    @squad = Squad.find(params[:id])
  end
  

  def update
    puts "Debug: Params - #{params.inspect}"
    if @squad.update(squad_params)
      redirect_to @squad, notice: 'Squad was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @squad.destroy
    redirect_to squads_url, notice: 'Squad was successfully destroyed.'
  end

  private

  def set_squad
    @squad = Squad.find(params[:id])
    puts "Debug: #{@squad.inspect}"
  end

  def squad_params
    params.require(:squad).permit(:name, :user_id, squad_players_attributes: [:id, :player_id, :position, :_destroy])
  end  
end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/squads/_mini_player_card.html.erb
<div class="mini-player-card bg-white shadow-lg rounded-lg overflow-hidden w-28 h-40 sm:w-32 sm:h-44 md:w-36 md:h-48 lg:w-40 lg:h-52 xl:w-44 xl:h-56 2xl:w-48 2xl:h-60 mt-5 mx-auto">
  <%= link_to player_path(player.api_id), class: "block h-full" do %>
    <% image_path = player_image_path(player.api_id) %>
    <div class="flex items-center justify-center mt-1 h-1/3">
      <%= image_tag(image_path, alt: player.name, class: "w-12 h-12 sm:w-14 sm:h-14 md:w-16 md:h-16 lg:w-18 lg:h-18 xl:w-20 xl:h-20 2xl:w-22 2xl:h-22 object-cover object-center") %>
    </div>
    <div class="px-2 py-1 flex flex-col items-center h-2/3">
      <h3 class="player-name font-bold text-xs sm:text-sm md:text-sm lg:text-lg xl:text-lg 2xl:text-lg text-gray-900 mb-1 text-center truncate w-full" style="max-height: 3rem;"><%= player.name %></h3>
      <div class="flex items-center justify-center mb-1">
        <span class="text-xs font-bold text-gray-800 mr-2"><%= player.rating %></span>
        <span class="text-xs text-gray-600"><%= player.position %></span>
      </div>
      <div class="grid grid-cols-2 gap-1 text-xs font-semibold text-gray-800 mb-1 hidden sm:grid">
        <span><%= player.pace %> PAC</span>
        <span><%= player.shooting %> SHO</span>
        <span><%= player.passing %> PAS</span>
        <span><%= player.dribbling %> DRI</span>
        <span><%= player.defending %> DEF</span>
        <span><%= player.physicality %> PHY</span>
      </div>
      <div class="mt-1 flex items-center space-x-2 p-1">
      <%= image_tag(nation_image_path(player.nation), alt: "Nation Flag", class: "w-4 h-4 sm:w-4 sm:h-4 md:w-4 md:h-4 lg:w-5 lg:h-5") if player.nation.present? %>
      <%= image_tag(club_image_path(player.club), alt: "Club Flag", class: "w-4 h-4 sm:w-4 sm:h-4 md:w-4 md:h-4 lg:w-5 lg:h-5") if player.club.present? %>
      </div>
    </div>
  <% end %>
  <% if defined?(editable) && editable %>
  <%= button_to squad_squad_player_path(squad, squad_player), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red-500 hover:text-red-700' do %>
    <i class="fas fa-trash-alt"></i>
  <% end %>  
  <% end %>
</div>

app/views/squads/_position_field.html.erb
<% squad_player = squad.squad_players.find_by(position: position) %>
<div class="field mt-12">
  <% if squad_player && squad_player.player %>
    <%= render 'mini_player_card', player: squad_player.player, editable: editable, squad: squad, squad_player: squad_player %>
    <% if editable %>
      <%= link_to squad_squad_player_path(squad, squad_player), method: :delete, class: 'text-red-500 hover:text-red-700' do %>
        <i class="fas fa-times"></i>
      <% end %>
    <% end %>
  <% else %>
  <%= link_to "Add #{position}", new_for_squad_player_path(squad_id: squad.id, position: position), class: "add-player-button w-32 h-32 md:w-40 lg:w-48 px-4 py-2 bg-gray-300 rounded hover:bg-gray-400 text-center truncate" %>
  <% end %>
</div>

app/views/squads/edit.html.erb
<h1 class="text-xl font-bold mb-4 text-gray-200">Edit Squad: <%= @squad.name %></h1>

<%= form_with(model: @squad, local: true, method: :patch) do |form| %>
  <div class="mb-4">
    <%= form.label :name, class: "block text-sm font-medium text-gray-200" %>
    <%= form.text_field :name, class: "text-gray-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
  </div>
  <div class="flex justify-center mt-6">
    <%= form.submit "Update Squad Name", class: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600" %>
  </div>
<% end %>

<%= link_to 'Back to Squads', squads_path, class: 'text-blue-400 hover:underline mt-4 block' %>

app/views/squads/index.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
<div class="bg-gray-600 rounded-lg p-10">
  <h1 class="text-3xl font-bold text-white mb-6">My Squads</h1>
  <div class="mb-6">
    <%= link_to 'New Squad', new_squad_path, class: 'inline-block bg-blue-500 text-white font-bold py-2 px-4 rounded hover:bg-blue-600' %>
  </div>
  <ul class="bg-white rounded-lg shadow divide-y divide-gray-200">
    <% @my_squads.each do |squad| %>
      <li class="px-6 py-6 flex justify-between items-center">
        <%= link_to squad.name, squad_path(squad), class: 'text-xl font-medium text-gray-900 mr-8' %>
        <div>
          <%= link_to edit_squad_path(squad), class: 'inline-flex items-center bg-gray-300 text-gray-800 font-medium py-2 px-4 rounded hover:bg-gray-400 mr-4' do %>
            <span class="material-icons">edit</span>
          <% end %>
          <%= button_to squad_path(squad), method: :delete, data: { confirm: 'Are you sure?' }, class: 'inline-flex items-center bg-gray-300 text-gray-800 font-medium py-2 px-4 rounded hover:bg-gray-400' do %>
            <span class="material-icons">delete</span>
          <% end %>      
        </div>
      </li>
    <% end %>
  </ul>
  </div>

  <div class="bg-gray-600 rounded-lg p-10 mt-5">
  <h1 class="text-3xl font-bold text-white mb-6 mt-12">User Squads</h1>
  <ul class="bg-white rounded-lg shadow divide-y divide-gray-200">
    <% @user_squads.each do |squad| %>
      <li class="px-6 py-6 flex justify-between items-center">
        <%= link_to squad.name, squad_path(squad), class: 'text-xl font-medium text-gray-900 mr-8' %>
        <div>
          <%= link_to 'View', squad_path(squad), class: 'inline-flex items-center bg-gray-300 text-gray-800 font-medium py-2 px-4 rounded hover:bg-gray-400' %>
        </div>
      </li>
    <% end %>
  </ul>
</div>
</div>

app/views/squads/new.html.erb
<h1 class="text-xl text-white font-bold mt-4 mb-4">Create a New Squad</h1>

<%= form_with(model: @squad, local: true) do |form| %>
  <div class="flex justify-center mb-4">
    <%= form.label :name, class: 'text-white block text-sm font-medium text-gray-700' %>
    <%= form.text_field :name, class: 'mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 w-1/2' %>
  </div>

  <div class="position-container flex justify-center gap-4 mb-4 font-bold">
  <% ['LW', 'ST', 'RW'].each do |position| %>
  <%= render 'position_field', position: position, form: form, squad: @squad, editable: false %>
  <% end %>
  </div>

  <div class="position-container flex justify-center gap-4 mb-4 font-bold">
    <% ['CM', 'LCM', 'RCM'].each do |position| %>
      <%= render 'position_field', position: position, form: form, squad: @squad, editable: false %>
    <% end %>
  </div>

  <div class="position-container flex justify-center gap-4 mb-4 font-bold">
    <% ['LB', 'LCB', 'RCB', 'RB'].each do |position| %>
      <%= render 'position_field', position: position, form: form, squad: @squad, editable: false %>
    <% end %>
  </div>

  <div class="position-container flex justify-center gap-4 mb-4 font-bold">
    <%= render 'position_field', position: 'GK', form: form, squad: @squad, editable: false %>
  </div>

  <div class="flex justify-center mt-10 actions">
    <%= form.submit 'Create Squad', class: 'px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600' %>
  </div>
<% end %>

<%= link_to 'Back to Squads', squads_path, class: 'text-blue-400 hover:underline' %>

app/views/squads/show.html.erb
<h1 class="text-2xl font-bold text-center mt-4 mb-6 text-gray-200"><%= @squad.name %></h1>

<% attackers = @squad.squad_players.where(position: ['LW', 'ST', 'RW']).sort_by { |sp| ['LW', 'ST', 'RW'].index(sp.position) } %>
<div class="bg-gray-300 p-4 rounded-lg mt-4 mb-4">
<div class="text-center mb-2 font-bold text-lg lg:text-xl xl:text-2xl">Attackers</div>
  <div class="flex flex-wrap justify-center gap-4">
    <% attackers.each do |squad_player| %>
      <%= render 'mini_player_card', player: squad_player.player %>
    <% end %>
  </div>
</div>


<% midfielders = @squad.squad_players.where(position: ['LCM', 'CM', 'RCM']).sort_by { |sp| ['LCM', 'CM', 'RCM'].index(sp.position) } %>
<div class="bg-gray-300 p-4 rounded-lg mb-4">
<div class="text-center mb-2 font-bold text-lg lg:text-xl xl:text-2xl">Midfielders</div>
  <div class="flex flex-wrap justify-center gap-4">
    <% midfielders.each do |squad_player| %>
      <%= render 'mini_player_card', player: squad_player.player %>
    <% end %>
  </div>
</div>

<% defenders = @squad.squad_players.where(position: ['LB', 'LCB', 'RCB', 'RB']).sort_by { |sp| ['LB', 'LCB', 'RCB', 'RB'].index(sp.position) } %>
<div class="bg-gray-300 p-4 rounded-lg mb-4">
<div class="text-center mb-2 font-bold text-lg lg:text-xl xl:text-2xl">Defenders</div>
  <div class="flex flex-wrap justify-center gap-4">
    <% defenders.each do |squad_player| %>
      <%= render 'mini_player_card', player: squad_player.player %>
    <% end %>
  </div>
</div>

<div class="bg-gray-300 p-4 rounded-lg mb-4">
<div class="text-center mb-2 font-bold text-lg lg:text-xl xl:text-2xl">Goalkeeper</div>
  <div class="flex flex-wrap justify-center gap-4">
  <% @squad.squad_players.where(position: 'GK').each do |squad_player| %>
    <%= render 'mini_player_card', player: squad_player.player %>
  <% end %>
</div>
</div>